"""initial_schema

Revision ID: a3231281a2eb
Revises: 
Create Date: 2026-09-10 18:37:56.717510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3231281a2eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('pitch_number', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pitch_number')
    )
    op.create_table('tournaments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fixture_generated', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_single_active_tournament', 'tournaments', ['is_active'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('rounds',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', name='uq_round_number_per_tournament')
    )
    op.create_table('teams',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('delegate_name', sa.String(length=100), nullable=False),
    sa.Column('delegate_phone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'name', name='uq_team_name_per_tournament'),
    sa.UniqueConstraint('tournament_id', 'short_name', name='uq_team_short_name_per_tournament')
    )
    op.create_table('matches',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=False),
    sa.Column('away_team_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('away_score IS NULL OR away_score >= 0', name='chk_valid_away_score'),
    sa.CheckConstraint('home_score IS NULL OR home_score >= 0', name='chk_valid_home_score'),
    sa.CheckConstraint('home_team_id <> away_team_id', name='chk_different_match_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_pitch_date_time', 'matches', ['pitch_id', 'match_date', 'start_time'], unique=False)
    op.create_index('idx_match_round', 'matches', ['round_id'], unique=False)
    op.create_table('players',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'jersey_number', name='uq_team_jersey_number')
    )
    op.create_index(op.f('ix_players_dni'), 'players', ['dni'], unique=True)
    op.create_table('standings',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_diff', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('fair_play_score', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_id', name='uq_team_per_tournament_standing')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('match_stats',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('goals >= 0', name='chk_valid_player_goals'),
    sa.CheckConstraint('red_cards >= 0 AND red_cards <= 1', name='chk_valid_red_cards'),
    sa.CheckConstraint('yellow_cards >= 0 AND yellow_cards <= 2', name='chk_valid_yellow_cards'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_player_match_stats')
    )
    # ### end Alembic commands ###

    # PostgreSQL specific extensions, triggers and constraints
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")

    # 1. Immutability Function & Trigger for Matches
    op.execute("""
    CREATE OR REPLACE FUNCTION check_match_score_immutability()
    RETURNS TRIGGER AS $$
    BEGIN
        IF OLD.status = 'JUGADO' AND (OLD.home_score IS DISTINCT FROM NEW.home_score OR OLD.away_score IS DISTINCT FROM NEW.away_score) THEN
            RAISE EXCEPTION 'No se puede modificar el resultado de un partido que ya fue jugado (inmutable)';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("DROP TRIGGER IF EXISTS trg_match_score_immutability ON matches;")
    op.execute("""
    CREATE TRIGGER trg_match_score_immutability
    BEFORE UPDATE ON matches
    FOR EACH ROW
    EXECUTE FUNCTION check_match_score_immutability();
    """)

    # 2. Prevent Team Double-Booking in the same round
    op.execute("""
    CREATE OR REPLACE FUNCTION check_team_single_match_per_round()
    RETURNS TRIGGER AS $$
    DECLARE
        conflict_count INT;
    BEGIN
        SELECT COUNT(*) INTO conflict_count
        FROM matches
        WHERE round_id = NEW.round_id
          AND id <> NEW.id
          AND status <> 'CANCELADO'
          AND (home_team_id IN (NEW.home_team_id, NEW.away_team_id)
               OR away_team_id IN (NEW.home_team_id, NEW.away_team_id));

        IF conflict_count > 0 THEN
            RAISE EXCEPTION 'Un equipo no puede jugar dos partidos en la misma fecha (round_id: %)', NEW.round_id;
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("DROP TRIGGER IF EXISTS trg_team_single_match_per_round ON matches;")
    op.execute("""
    CREATE TRIGGER trg_team_single_match_per_round
    BEFORE INSERT OR UPDATE ON matches
    FOR EACH ROW
    EXECUTE FUNCTION check_team_single_match_per_round();
    """)

    # 3. Prevent Pitch and Time Overlap using btree_gist
    op.execute("""
    ALTER TABLE matches ADD CONSTRAINT no_pitch_overlap
    EXCLUDE USING gist (
        pitch_id WITH =,
        match_date WITH =,
        tsrange(('2000-01-01'::date + start_time), ('2000-01-01'::date + end_time)) WITH &&
    ) WHERE (status <> 'CANCELADO');
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_stats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('standings')
    op.drop_index(op.f('ix_players_dni'), table_name='players')
    op.drop_table('players')
    op.drop_index('idx_match_round', table_name='matches')
    op.drop_index('idx_match_pitch_date_time', table_name='matches')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('rounds')
    op.drop_index('uq_single_active_tournament', table_name='tournaments', postgresql_where=sa.text('is_active = true'))
    op.drop_table('tournaments')
    op.drop_table('pitches')
    # ### end Alembic commands ###
